### ISSUE TITLE
Wiki porting TODO

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#1159]
- [ ] Landing page Spanish
- [ ] Landing page German
- [ ] Landing page Bulgarian
- [ ] Check all pages English
- [ ] Check all pages German
- [ ] Check all pages Bulgarian
- [ ] Check unlinked pages
- [ ] Link to OpenAPS read-the-docs where appropriate

**Comment by typ1-brods** [comment]
I'm working on German pages at the moment. Hoping the new github solution is easy to use for a noob :-)

**Comment by typ1-brods** [comment]
Would it be an idea to make different instances for each lanuage instead of using one single main menu for all together?

**Comment by AdrianLxM** [comment]
@typ1-brods the mayority was in favour of having all in one menu and then do different landing pages like 
en.androidaps.org, de.androidaps.org

One more remark: When doing fixes etc. it is good to do so on the german version. Highly appreciated! When adding new things it would be good to have them in English as well.
Thanks a lot!

**Comment by typ1-brods** [comment]
What's about a language menu solution like here? http://androidaps-user-guide.readthedocs.io/en/latest/de/index.html# 
That would be more clear maybe.

**Comment by AdrianLxM** [comment]
@typ1-brods in my opinion: Yes to both! Would be great if you could work on that and do a PR!
