### ISSUE TITLE
SMB TODO - (2.0 only wiki)

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#646]
* Check that SMB don't re-trigger a loop cycle
* Check IOBpredict / guardBG
* Move bolussnooze_dia_divisor to AMA

To wiki:
* lower autosens back to 1.2
* changed meaning of IOB

**Comment by AdrianLxM** [comment]
Alarm for Carbs-Required?

**Comment by jotomo** [comment]
### Bolus cancellation

**jotomo**: if an SMB is running in the background, a new bolus is requested and then attempted to cancel: this will likely cancel the SMB and then run the bolus.
**adrian**: How  about solving this on a higher level upstream? This most likely will  affect the other pump models that read history (Dana Rv2, Dana RS) or  probably even all pumps to some extent. My idea would be: on a bolus cancel always clear the CommandQueue of any bolus types (SMB or standard).  
* If a standard bolus is delivered and cancelled, an SMB should not  follow anyways as a new evaluation of the situation will be done  afterwards with the new IOB reality.
* If an SMB is delivered and cancelled (no problem if one is missing  as they are micro), the user actually would want to cancel the manually  triggered one -> delete it from the queue.

**Comment by jotomo** [comment]
> Alarm for Carbs-Required?

Will require _bolussnooze_-like logic since `carbsRequired` frequently skyrockets after a meal, before carbs kick in, might take a few iterations to go down after carb intake as well.

**Comment by jotomo** [comment]
- [ ] GL 364 handle deviation outliers
- [ ] GL 367 COB issues

**Comment by jotomo** [comment]
- [ ] In `ConfigBuilderPlugin.applyAPSRequest`, a TBR is not set again if it's running for at least another 5m. With SMB this can lead to too much delivered insulin, if the basal insulin for the next 2h is delivered as SMB and relies on a 0% TBR to take that insulin away. Setting a TBR each and every time, to extend e.g. from 115m to 120m. every 5m is probably overkill, but maybe round to 15m or 30m, e.g. when 'rounding' to 15m, don't apply a request for 120m 0% if remaining TBR duration is 115m or 110m, but extend it when it reaches 105, thereby extending the TBR by 15m.
P.S. oref1 0.6.1 will reduce the max duration of a 0% TBR to 60m if I'm not mistaken.

**Comment by McHoffi** [comment]
- [ ] Change "Notify on SMB" in Wear settings default value to true, so you do "feel" it especially in the beginning when there is given a SMB

**Comment by jotomo** [comment]
- [ ] All basal lines in graph are missing (default, TBR), if displayed time consists of 0% TBR(s).

**Comment by jotomo** [comment]
- [ ] Look into simplifying _EventOverviewBolusProgress_, see https://github.com/MilosKozak/AndroidAPS/pull/755/commits/30680892971dbe807ab3551b209405f5006b4e59#r173672762

**Comment by AdrianLxM** [comment]
@jotomo @MilosKozak 
Do we need an alarm for Carbs-Required?

@jotomo 
What was the "deviation outliers" part?

The rest is only what we have to add to the Wiki and does not change the AAPS code base

**Comment by jotomo** [comment]
>  Do we need an alarm for Carbs-Required?

A low predict / carb suggestion would be nice, but I'd say not for 2.0 as we'll need a way to snooze an alarm, show snooze state, an option to unsnooze, configurability and all that jazz.

**Comment by jotomo** [comment]
- [ ] Docs: Update Combo-pages to refer to `master` branches instead of `combo` (create `master` in _ruffy_ repo)
